version: '3.8'
services:
  
  web:
    container_name: FastAPI
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web, websecure"
      - "traefik.http.routers.api.rule=Host(`api.virmin8.uk`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=80"
    volumes:
     - .:/app

    networks:
      - traefik_default

networks:
  traefik_default:
    external: true